name: build bj-room-web

on:
  push:
    branches:
      - 'master'
    paths:
      - 'web/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: Build and push Web
        uses: docker/build-push-action@v2
        with:
          context: web
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/liubaicai/bj-room-web:latest